server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
      
security:
  oauth2:
    resource:
      userInfoUri: http://${security.oauth2.resource.hostname}:8084/user
      id: baseb
      
spring:
  data:
    mongodb:
      port: 27017
      database: baseb
