server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
      
security:
  oauth2:
    resource:
      userInfoUri: http://${security.oauth2.resource.hostname}:8084/user
      id: basea
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basea?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: basea
  jpa:
    database: mysql
