server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
      
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: baseb
