server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
      
security:
  oauth2:
    resource:
      userInfoUri: http://${security.oauth2.resource.hostname}:8084/user
      id: basec
      
spring:
  redis:
    port: 6379
