server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
      
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8084/user
      id: basec
      
spring:
  redis:
    host: localhost
    port: 6379
